= Setting Up OSX for Python Development
:published_at: 2014-11-27

This is where I will record my method for setting up my Mac for Python development.  I focus on scientific computing and machine learning, but I do some web and application development as well.

[[mavericks-10.9.5]]
Mavericks (10.9.5)
~~~~~~~~~~~~~~~~~~

[[preparation]]
Preparation
^^^^^^^^^^^

Begin by fixing your PATH variable as described here: http://hackercodex.com/guide/mac-osx-mavericks-10.9-configuration/

Install Xcode via the app store or terminal as described in the previous link

Install Homebrew:

....
$ ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)”
....

Install Python with Homebrew:

....
$ brew install python
....

If this worked properly, `$ which python` should return: `/usr/local/bin/python`

Here, you may need to run:

....
$ brew linkapps
....

You will need some compilers and other requirements for some popular Python packages:

....
$ brew install freetype
....

....
$ brew install gfortran
....

or since gcc now includes gfortran

....
$ brew install gcc
....

[[virtualenv]]
Virtualenv
^^^^^^^^^^

Now we are ready to start creating some virtual environments. Virtualenv allows us to create many separate python interpreters, each with their own set of installed packages. YOU SHOULD NEVER DEVELOP IN PYTHON WITHOUT USING VIRTUALENV. If you don't believe me, or are entirely new to Python, stop to read more here: http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/

....
$ pip install virtualenv
....

I prefer to put all my Python virtual environments in `~/pythonEnvs`:

....
$ mkdir ~/pythonEnvs
....

[[scientific-environment]]
Scientific Environment
^^^^^^^^^^^^^^^^^^^^^^

Now setup a scientific development environment

....
$ virtualenv ~/pythonEnvs/scientificEnv
....

....
$ source ~/pythonEnvs/scientificEnv/bin/activate
....

....
(scientificEnv)$ pip install numpy
....

....
(scientificEnv)$ pip install scipy
....

....
(scientificEnv)$ pip install matplotlib
....

....
(scientificEnv)$ pip install scikit-learn
....

....
(scientificEnv)$ pip install pybrain
....

....
(scientificEnv)$ pip install statsmodels
....

....
(scientificEnv)$ deactivate
....

[[gui-development]]
GUI Development
^^^^^^^^^^^^^^^

I often use tkinter for simple GUI development, but more complex interfaces require something a little more powerful. For this I prefer PyQT. However, the installation can be tricky to get right.

....
$ brew install qt --developer --with-d-bus --with-docs --with-mysql --with-qt3support
....

The QT designer executable will be in  /usr/local/Cellar/qt/4.8.5

....
$ brew install pyqt
....

....
$ brew tap homebrew/versions
....

....
$ brew install --python --qt vtk5
....

Notice that PyQT installed to the homebrew Python installation. At the time of this posting, this is the only way I could get a good install of PyQT. To create a virtualenv that inherits homebrew installation's packages use:

....
$ virtualenv --system-site-packages /path/to/new/env 
....

[[web-development]]
Web Development
^^^^^^^^^^^^^^^

I am not a web developer... But in my opinion every developer should be able to create a web app with some basic functionalities. For that I use the Flask micro-framework.

....
$ virtualenv ~/pythonEnvs/webEnv
....

....
$ source ~/pythonEnvs/webEnv/bin/activate
....

....
(webEnv)$ pip install flask
....

....
(webEnv)$ pip install flask-mysql
....

....
(webEnv)$ pip install flask-basicauth
....

....
(webEnv)$ pip install flask-lesscss
....

This will give you an environment that will allow you to connect to a MySQL database, have basic http authentication, and create apps with LESS styling (which seems to be a big part of bootstrap).

NOTE: There is a bug in flask-lesscss that has a simple fix: https://bitbucket.org/sjl/flask-lesscss/issue/1/static-path-error

[[final-notes]]
Final Notes
^^^^^^^^^^^

Hopefully this was helpful to someone who is either new to Python, new to OSX, or both. I have shown you how to create three generic python environments, but keep in mind that it is best practice to create a new environment for each project you make.
